name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Cache do Cypress
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-cache-${{ runner.os }}-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências do backend
        working-directory: backend
        run: npm ci

      - name: Rodar testes da API
        working-directory: backend
        run: npm run test

      - name: Instalar dependências do frontend
        working-directory: frontend
        run: npm ci

      - name: Instalar dependências do Cypress
        working-directory: cypress
        run: npm ci

      - name: Instalar binário do Cypress
        working-directory: cypress
        run: npx cypress install

      - name: Rodar testes E2E com Cypress
        working-directory: cypress
        run: npx cypress run
